spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

#custom variables
jwt:
  secret:
    key: "ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength"
    expirationTime: "28800"
